name: review2
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.9.0
  - dash
  - flask-caching
  - geopandas
  - gunicorn
  - h5py
  - matplotlib
  - pathos
  - pip
  - scipy
  - spyder
  - tqdm
  - tk
  - pip:
    - colorama
    - us
