name: review2
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.9.0
  - dash
  - flask-caching
  - geopandas
  - gunicorn
  - h5py
  - matplotlib
  - pathos
  - postgresql
  - pip
  - psycopg2
  - scipy
  - spyder
  - sqlalchemy
  - tqdm
  - tk
  - pip:
    - addfips
    - colorama
    - us
    - flask-sqlalchemy
