name: review
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.7.0
  - dash
  - dask
  - flask-caching
  - geopandas
  - gunicorn
  - h5py
  - matplotlib
  - rasterio
  - spyder
  - tqdm
  - tk
