name: review
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.8
  - dash
  - dask
  - flask-caching
  - gdal
  - h5py
  - netcdf4
  - postgresql
  - psycopg2
  - rasterio
  - spyder
  - tqdm
  - xarray

