name: review
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.8
  - dash
  - dash_auth
  - dask
  - flask-caching
  - gdal
  - geopandas
  - gunicorn
  - esmpy
  - h5py
  - netcdf4
  - postgresql
  - psycopg2
  - rasterio
  - rioxarray
  - scipy
  - spyder
  - tqdm
  - xarray
  - xesmf
